# Generated by Django 3.2 on 2022-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_company',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
