# Generated by Django 3.2 on 2022-05-22 11:28

from django.db import migrations


class Migration(migrations.Migration):
    def custom_migrations(self, schema_editor):
        Company = self.get_model('account', 'Company')
        for company in Company.objects.all():
            company.title = company.title.upper()
            company.save()

    dependencies = [
        ('account', '0002_auto_20220508_0934'),
    ]

    operations = [
        migrations.RunPython(custom_migrations, migrations.RunPython.noop)
    ]
